-- MySQL Script generated by MySQL Workbench
-- Sun Nov 24 15:05:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Favourites list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Favourites list` (
  `listId` INT NOT NULL,
  `userId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`listId`, `userId`),
  UNIQUE INDEX `idFavourites list_UNIQUE` (`listId` ASC) VISIBLE,
  UNIQUE INDEX `Favourites listcol_UNIQUE` (`userId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `userId` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `Favourites list_listId` INT NOT NULL,
  PRIMARY KEY (`userId`, `Favourites list_listId`),
  UNIQUE INDEX `idUser_UNIQUE` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `Usercol_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_User_Favourites list_idx` (`Favourites list_listId` ASC) VISIBLE,
  CONSTRAINT `fk_User_Favourites list`
    FOREIGN KEY (`Favourites list_listId`)
    REFERENCES `mydb`.`Favourites list` (`listId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movies` (
  `movieId` INT NOT NULL,
  `movieTitle` VARCHAR(45) NOT NULL,
  `relaseDate` VARCHAR(45) NULL,
  `movieGenre` VARCHAR(45) NULL,
  `movieDescription` VARCHAR(45) NULL,
  `screeningTime` VARCHAR(45) NULL,
  PRIMARY KEY (`movieId`, `movieTitle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favourite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Favourite` (
  `Movies_idMovies` INT NOT NULL,
  `Favourites list_listId` INT NOT NULL,
  PRIMARY KEY (`Movies_idMovies`, `Favourites list_listId`),
  INDEX `fk_Favourite_Favourites list1_idx` (`Favourites list_listId` ASC) VISIBLE,
  CONSTRAINT `fk_Favourite_Movies1`
    FOREIGN KEY (`Movies_idMovies`)
    REFERENCES `mydb`.`Movies` (`movieId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favourite_Favourites list1`
    FOREIGN KEY (`Favourites list_listId`)
    REFERENCES `mydb`.`Favourites list` (`listId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Group`
-- -----------------------------------------------------
create table if not exists `mydb`."group" (
	`id` serial primary key,
	`groupName` varchar(255) not null,
	`groupDescription` varchar(255),
  `groupImage` text,
	`owner` varchar(255) not null)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`."messages" (
	`id` serial primary key,
	`group_id` int references "group"(id),
	`username` varchar(255) not null,
	`text` text not null,
	`timestamp` timestamp default current_timestamp)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`GroupMembers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GroupMembers` (
  `idGroupMembers` VARCHAR(45) NOT NULL,
  `userId` INT NOT NULL,
  `groupId` VARCHAR(45) NULL,
  `Group_idGroup` INT NOT NULL,
  INDEX `fk_GroupMembers_User1_idx` (`userId` ASC) VISIBLE,
  PRIMARY KEY (`idGroupMembers`, `userId`, `Group_idGroup`),
  INDEX `fk_GroupMembers_Group1_idx` (`Group_idGroup` ASC) VISIBLE,
  CONSTRAINT `fk_GroupMembers_User1`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GroupMembers_Group1`
    FOREIGN KEY (`Group_idGroup`)
    REFERENCES `mydb`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
